# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  schedule:
    # Runs at 22:00 UTC every day (see https://crontab.guru)
    - cron: '0 16 * * *'
  push:
    branches:
      - main 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4 requests
    
    - name: Verify Commit Status for this day
      run: |
        python ./main.py ${{ secrets.PUSH_API_KEY }}
